### ISSUE TITLE
DB Cleaner is cleaning my development DB ! 😭

### ISSUE THREAD

**Issue by dfabreguette-ap** [DatabaseCleaner/database_cleaner-mongoid#13]
Since recently, database_cleaner gem is cleaning out my development database alongside with Rails, Rspec and mongoid ORM.
I followed all suggested solutions here : https://stackoverflow.com/questions/30784955/database-cleaner-is-wiping-my-development-database but none worked.
Looks like RAILS_ENV is set properly in each steps :

spec/rails_helper.rb
```ruby
  config.before(:suite) do
    DatabaseCleaner[:mongoid].strategy = :deletion
  end

  config.before(:each) do
    DatabaseCleaner[:mongoid].start
  end

  config.after(:each) do
    DatabaseCleaner[:mongoid].clean
  end
```

I checked out v1.8.5, it didn't work either.

Any idea how we can debug this ?

**Comment by botandrose** [comment]
Hi @dfabreguette-ap ! If you can share a repo that reproduces this issue, I'd be happy to take a look and figure out where the problem is!

**Comment by Victorcorcos** [comment]
Did you try to change the database name on the `DatabaseCleaner` configurations?

```rb
DatabaseCleaner[:mongoid].db = :your_database
```

**Comment by dfabreguette-ap** [comment]
My bad, problem was my mongoid database configuration file configured with same database in test and development database name 😅
